
// Objective-C API for talking to the following Go packages
//
//	vsys
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Vsys_FRAMEWORK_H__
#define __Vsys_FRAMEWORK_H__

#include "Vsys.objc.h"
#include "Universe.objc.h"

#endif
